import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from './useAuth';

// This VAPID public key will be generated by the edge function on first call
const VAPID_PUBLIC_KEY_STORAGE = 'vapid_public_key';

function urlBase64ToUint8Array(base64String: string) {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

export const usePushNotifications = () => {
  const { user } = useAuth();
  const [permission, setPermission] = useState<NotificationPermission>(
    typeof Notification !== 'undefined' ? Notification.permission : 'default'
  );
  const [supported] = useState(() => 'serviceWorker' in navigator && 'PushManager' in window);

  // Sync permission state with browser (e.g. if user grants via browser prompt)
  useEffect(() => {
    if (typeof Notification !== 'undefined') {
      setPermission(Notification.permission);
    }
  }, []);

  const subscribe = async () => {
    if (!supported || !user) return false;

    try {
      const perm = await Notification.requestPermission();
      setPermission(perm);
      if (perm !== 'granted') return false;

      const registration = await navigator.serviceWorker.register('/sw.js');
      await navigator.serviceWorker.ready;

      // Get VAPID public key from edge function
      const { data: vapidData } = await supabase.functions.invoke('get-vapid-key');
      if (!vapidData?.publicKey) {
        console.error('No VAPID public key returned');
        return false;
      }

      const subscription = await (registration as any).pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: urlBase64ToUint8Array(vapidData.publicKey),
      });

      const subJson = subscription.toJSON();

      await supabase.from('push_subscriptions').upsert(
        {
          user_id: user.id,
          endpoint: subJson.endpoint!,
          p256dh: subJson.keys!.p256dh!,
          auth: subJson.keys!.auth!,
        },
        { onConflict: 'user_id,endpoint' }
      );

      // Re-sync permission state after successful subscription
      setPermission('granted');
      return true;
    } catch (err) {
      console.error('Push subscription failed:', err);
      // Still update permission state even on error
      if (typeof Notification !== 'undefined') {
        setPermission(Notification.permission);
      }
      return false;
    }
  };

  // Auto-register if already granted
  useEffect(() => {
    if (supported && user && permission === 'granted') {
      subscribe();
    }
  }, [user, supported, permission]);

  return { supported, permission, subscribe };
};
